-- CreateTable
CREATE TABLE "SimilarUsers" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "rent" DOUBLE PRECISION,
    "utilities" DOUBLE PRECISION,
    "housing" DOUBLE PRECISION,
    "loans" DOUBLE PRECISION,
    "student_loans" DOUBLE PRECISION,
    "car_loans_and_lease" DOUBLE PRECISION,
    "credit_card_payments" DOUBLE PRECISION,
    "other_loans" DOUBLE PRECISION,
    "entertainment" DOUBLE PRECISION,
    "streaming_services" DOUBLE PRECISION,
    "other_entertainment" DOUBLE PRECISION,
    "food" DOUBLE PRECISION,
    "restaurants" DOUBLE PRECISION,
    "groceries" DOUBLE PRECISION,
    "medical_care" DOUBLE PRECISION,
    "transportation" DOUBLE PRECISION,
    "gas" DOUBLE PRECISION,
    "parking" DOUBLE PRECISION,
    "ride_share" DOUBLE PRECISION,
    "public_transit" DOUBLE PRECISION,
    "other_transportation" DOUBLE PRECISION,
    "merchandise" DOUBLE PRECISION,
    "retail" DOUBLE PRECISION,
    "apparel" DOUBLE PRECISION,
    "e_commerce" DOUBLE PRECISION,
    "electronics" DOUBLE PRECISION,
    "pet_supplies" DOUBLE PRECISION,
    "super_stores" DOUBLE PRECISION,
    "other_merchandise" DOUBLE PRECISION,
    "other_expenses" DOUBLE PRECISION,
    "gym_membership" DOUBLE PRECISION,
    "financial_planning" DOUBLE PRECISION,
    "legal_services" DOUBLE PRECISION,
    "insurance" DOUBLE PRECISION,
    "tax_payments" DOUBLE PRECISION,
    "travel" DOUBLE PRECISION,
    "investment_and_saving" DOUBLE PRECISION,
    "investment" DOUBLE PRECISION,
    "savings_account" DOUBLE PRECISION,

    CONSTRAINT "SimilarUsers_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "SimilarUsers" ADD CONSTRAINT "SimilarUsers_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
